---

# basic installation for a host


# fail if it's not a Red Hat or Debian based system
- name: Check OS (common)
  fail: msg="Not a Red Hat or Debian based system!"
  when: ansible_distribution != 'CentOS' and ansible_distribution != 'Red Hat Enterprise Linux' and ansible_distribution != 'Debian' and ansible_distribution != 'Ubuntu'


- name: Installation for Red Hat like systems
  include: redhat.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'


- name: Installation for Debian like systems
  include: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
